### ISSUE TITLE
Padding make leon block too narrow!

### ISSUE THREAD

**Issue by caprenter** [CooperativeIT/assistb5subtheme#56]
![Image 10-01-2023 at 16 11](https://user-images.githubusercontent.com/185467/211606790-5180c894-85e9-4cf1-a281-2bec9a93a46f.jpg)
https://github.com/CooperativeIT/assistb5subtheme/blob/e34fa531aab53845bc6b9aaeca1b176d81c8aca8/scss/style.scss#L632

**Comment by Plebster** [comment]
it's not just the Leon block, it's everything after it as well

**Comment by Plebster** [comment]
re opened original issue
